### ISSUE TITLE
Coveralls not posting coverage notification to PRs

### ISSUE THREAD

**Issue by mikeengland** [AndreMiras/coveralls-python-action#2]
Hi Andre, thanks very much for developing this library!

I am not sure if this is an issue with this library or not, but I have found that since using this action for pushing coveralls instead of my old Travis CI build, the coveralls coverage notification message is not being sent to PRs.

In Coveralls, the builds look fine so I am not sure if something strange is happening behind the scenes. Any ideas?

Thanks!

![image](https://user-images.githubusercontent.com/8333737/79552917-ffe97e80-809b-11ea-8778-8e8646a64cb6.png)

**Comment by AndreMiras** [comment]
Could you share the repo, branch and build so I can take a look?

**Comment by mikeengland** [comment]
The repo PR is https://github.com/kayak/pypika/pull/406. I re-enabled travis to see if that would trigger the notification but that also did not work. It may be an issues on the coveralls side.

**Comment by AndreMiras** [comment]
I think it's because this change didn't increase/decrease the coverage. See it appears on mouse over.
If you make later a change that decrease the coverage then it will pop red.
![image](https://user-images.githubusercontent.com/24973/79569191-7a73c780-80b7-11ea-88a0-eb6940acabb1.png)

**Comment by mikeengland** [comment]
Ok - mustn't be to do with your package then!

Strangely, I don't see that on PR 406. 
![image](https://user-images.githubusercontent.com/8333737/79569893-c8d59600-80b8-11ea-9697-11d0286ed560.png)

**Comment by mikeengland** [comment]
@AndreMiras I _think_ it may be because I am creating a PR from a fork, however your PR was created from the same repo.
