### ISSUE TITLE
Webhook response has changed causing build failures

### ISSUE THREAD

**Issue by mikeengland** [AndreMiras/coveralls-python-action#6]
Hi!

The post webhook response has changed and now includes the url and jobs e.g.
`{'done': True, 'url': 'https://coveralls.io/builds/33721975', 'jobs': 4}` however the assertion in this action is:
`assert response.json() == {"done": True}, response.json()`

Unless changed, all successful coveralls builds will fail.

**Comment by mikeengland** [comment]
A fix PR has already been created in https://github.com/AndreMiras/coveralls-python-action/pull/5

**Comment by AndreMiras** [comment]
Thanks for the report, PR was merged, closing
