### ISSUE TITLE
Build time

### ISSUE THREAD

**Issue by prisae** [AndreMiras/coveralls-python-action#9]
Thanks for creating this action, it works like a charm.

One question though: It always seems to take somewhere between 35-40 seconds to build (per parallel build plus the final submission build, so it adds up). Is there anything that could be done to speed this up? (Or, in other words: Is my implementation wrong, or is this build time just a fact that has to be accepted?)

![Selection_001](https://user-images.githubusercontent.com/8020943/100623114-feff1780-3321-11eb-9293-d9f38b1ae367.png)

Thanks!

**Comment by AndreMiras** [comment]
Hi prisae,
Yes it currently takes 35-40 seconds to build indeed. If you expand the build section you should see it's the time it requires to pull the docker base image (`python:3.8`) and building the container.
Our [Dockerfile](https://github.com/AndreMiras/coveralls-python-action/blob/v20201129/Dockerfile) is relatively minimalist so I'm not sure there's much we could do there.
Things I can think about still are:

- See if GitHub Actions now supports Python actions without Docker (it's possible for NodeJS actions)
- Try with smaller Python base image
- Publish our custom image to DockerHub so we could skip the `pip install coveralls` part
- Suggestions welcomed :smile:

**Comment by prisae** [comment]
Thanks. No problem at all, I just thought I'd ask, in case I use it wrongly. Feel free to close, unlike you want to keep track of the time-issue.

**Comment by AndreMiras** [comment]
OK clear :+1: 
I made an optimisation that should make it slightly faster nonetheless.
Later, I may give it a try to publish a custom docker image as well to optimise it further

**Comment by AndreMiras** [comment]
I've also implemented the custom Docker image publication to DockerHub, this further reduced the build time from ~20 seconds to ~15 seconds. So we got from ~30 seconds initially down to ~15 now.
Ideally this should be handled the upstream repo https://github.com/coveralls-clients/coveralls-python
I may share them this suggestion
Edit: suggestion shared https://github.com/coveralls-clients/coveralls-python/issues/246

**Comment by prisae** [comment]
Great stuff, thanks @AndreMiras!
